name: Notify Discord

on:
  push:
    branches:
      - main 

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Message
        run: |
            curl -H "Content-Type: application/json" \
                -X POST \
                -d '{"content":"Neuer Push im Repository!"}' \
                "${{ secrets.DISCORD_WEBHOOK_URL }}"